// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeLineManager.Data;

namespace TimeLineManager.Data.Migrations
{
    [DbContext(typeof(DatabaseDbContext))]
    [Migration("20200427121546_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("TimeLineManager.Data.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EndDate")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartDate")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Thumbnail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("TimeLineManager.Data.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Thumbnail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("TimeLineManager.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coupon")
                        .HasColumnType("text");

                    b.Property<double?>("CreatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Images")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<double?>("ScheduledTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Sticker")
                        .HasColumnType("text");

                    b.Property<string>("Survey")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<double?>("UpdatedAt")
                        .HasColumnType("REAL");

                    b.Property<string>("Video")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TimeLineManager.Data.Models.Sticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Stickers");
                });

            modelBuilder.Entity("TimeLineManager.Data.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EndDate")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartDate")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Thumbnail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Surveys");
                });
#pragma warning restore 612, 618
        }
    }
}
